language: generic
sudo: required
dist: trusty
env:
- SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a
install:
- mkdir swift
- curl https://swift.org/builds/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
script:
- env PATH=$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH swift build
