language: generic
dist: trusty
env:
  global:
    - SWIFTENV_ROOT=$HOME/.swiftenv
    - PATH=$SWIFTENV_ROOT/bin:$PATH

install:
  - git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
before_script:
  - eval "$(swiftenv init -)"
  - swiftenv install 2.2-SNAPSHOT-2016-01-11-a
script:
  - swift build
